'''from tkinter import *#Managment page..
root8=Tk()
root8["bg"]="black"
root8.geometry('600x600')
labeld=Label(root8,text="Account Managment",bg="black",fg="white",font=("Helvetica", 36))
labeld.place(x=100,y=50)
label=Label(root8,text="Changing login Credentials",bg="black",fg="white",font=("Helvetica",20))
label.place(x=100,y=150)
button=Button(root8,text="Pin Changing",anchor=CENTER,bg="yellow",fg="red",padx=15,pady=10,font=("Helvetica", 16),relief="groove",command=lambda: pin(root8))
button.place(x=70,y=200)
button1=Button(root8,text="User-Name Change",anchor=CENTER,bg="yellow",fg="red",padx=15,pady=10,font=("Helvetica", 16),relief="groove",command=lambda: uname(root8))
button1.place(x=300,y=200)
label1=Label(root8,text="Changing Personal Details",bg="black",fg="white",font=("Helvetica", 20))
label1.place(x=100,y=280)
button2=Button(root8,text="Email Change",anchor=CENTER,bg="yellow",fg="red",padx=15,pady=10,font=("Helvetica", 16),relief="groove",command=lambda: email(root8))
button2.place(x=70,y=350)
button3=Button(root8,text="Account-Name Change",anchor=CENTER,bg="yellow",fg="red",padx=15,pady=10,font=("Helvetica", 16),relief="groove",command=lambda: aname(root8))
button3.place(x=300,y=350)
buttona=Button(root8,text="Home",command=lambda: home(root8),anchor=CENTER,bg="yellow",fg="red",padx=15,pady=10,font=("Helvetica", 16),relief="groove")
buttona.place(x=140,y=520)
buttonb=Button(root8,text="Logout",command=lambda: main(root8),anchor=CENTER,bg="yellow",fg="red",padx=15,pady=10,font=("Helvetica", 16),relief="groove")
buttonb.place(x=350,y=520)
root8.mainloop()'''

#User name changing..
from tkinter import *
root9=Tk()
root9["bg"]="black"
root9.geometry('600x600')
labeld=Label(root9,text="Account Managment",bg="black",fg="white",font=("Helvetica", 36))
labeld.place(x=100,y=50)
labela=Label(root9,text="Changing User-Name",bg="black",fg="white",font=("Helvetica", 20))
labela.place(x=140,y=130)
label=Label(root9,text="Old User-Name:",bg="black",fg="white",font=("Helvetica", 16))
label.place(x=60,y=180)
labelaa=Label(root9,text="Need to Enter",bg="black",fg="white",font=("Helvetica", 16))
labelaa.place(x=240,y=180)
labele=Label(root9,text="New User-Name:",bg="black",fg="white",font=("Helvetica", 16))
labele.place(x=60,y=230)
e=Entry(root9)
e.place(x=240,y=235)
buttonc=Button(root9,text="Change",command=lambda: alt1(root9,l,ch),anchor=CENTER,bg="yellow",fg="red",padx=15,pady=10,font=("Helvetica", 16),relief="groove")
buttonc.place(x=200,y=280)
buttona=Button(root9,text="Home",command=lambda: home(root9),anchor=CENTER,bg="yellow",fg="red",padx=15,pady=10,font=("Helvetica", 16),relief="groove")
buttona.place(x=140,y=400)
buttonb=Button(root9,text="Logout",command=lambda: main(root9),anchor=CENTER,bg="yellow",fg="red",padx=15,pady=10,font=("Helvetica", 16),relief="groove")
buttonb.place(x=350,y=400)
root9.mainloop()
